version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'cumplo_test'
      MYSQL_USER: 'user_cumplo'
      MYSQL_PASSWORD: 'secretpassword'

  web:
    build: .

    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py loaddata series tiies 
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
