# Generated by Django 3.0.1 on 2019-12-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesIndex',
            fields=[
                ('series_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('front_identifier', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
